# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PiktaleTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JSONParsing', '~> 0.1.8'
  pod 'SDWebImage'
  # Pods for PiktaleTask

  target 'PiktaleTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiktaleTaskUITests' do
    # Pods for testing
  end

end
